#!/usr/bin/env python3
"""Assign one editorial browsing collection per title; no external dependencies.

These rules intentionally infer only from a public title. They do not reproduce
organizer topic tags. Priority resolves overlap; specific subject matter wins
before broad social formats. Explicit overrides handle reviewed ambiguous titles.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
METHOD = ("Editorial primary collections inferred from public event titles using reviewed, deterministic rules and explicit overrides. "
          "Each event appears in exactly one collection. Specific subject matter usually takes precedence over a social format; "
          "sports, wellbeing activities and audience-specific gatherings use their stated purpose. Broad titles are grouped by "
          "format or as open discovery. Collections are designed for manageable browsing, not equal-sized quotas, official organizer "
          "tags, or event quality rankings. A title alone may omit relevant subjects; consult the organizer before choosing an event.")
COLLECTIONS = [
 ("agents-and-automation", "Agents & automation", "Agent orchestration, MCP, tools, workflows and deploying autonomous systems."),
 ("models-and-evaluation", "Models & evaluation", "Frontier models, training, reasoning, benchmarks, evaluation and AI research."),
 ("compute-and-cloud", "Compute & cloud", "Inference, GPUs, data centers, cloud platforms and AI infrastructure economics."),
 ("data-memory-and-search", "Data, memory & search", "Databases, retrieval, context, memory, knowledge and data infrastructure."),
 ("voice-and-conversation", "Voice & conversational AI", "Voice agents, conversational interfaces, speech and audio technology."),
 ("coding-and-devtools", "Coding & developer tools", "Software engineering, coding assistants, developer experience and production tooling."),
 ("security-and-governance", "Security, trust & governance", "Cybersecurity, privacy, AI safety, authorization, governance and public policy."),
 ("enterprise-ai", "Enterprise AI & workflows", "Adopting AI at work, organizational transformation and practical business automation."),
 ("product-and-design", "Product, design & UX", "Product management, design, user research, interfaces and product-market fit."),
 ("creative-media", "Creative AI, media & storytelling", "Film, music, creative tools, content production and the future of media."),
 ("consumer-and-commerce", "Consumer, commerce & experiences", "Consumer products, marketplaces, retail, fashion, gaming and customer experiences."),
 ("health-and-biotech", "Health, biotech & medicine", "Healthcare delivery, life sciences, drug discovery, medical devices and clinical AI."),
 ("wellbeing-and-longevity", "Wellbeing, longevity & reset", "Longevity, nutrition, mental wellbeing and restorative activities such as meditation or sauna."),
 ("robotics-and-hardware", "Robotics, hardware & physical AI", "Robots, hardware, manufacturing, sensors and intelligence in the physical world."),
 ("climate-and-frontier-tech", "Climate, energy & frontier science", "Climate, energy, sustainability, space, quantum computing and other frontier science."),
 ("fintech-and-payments", "Fintech, payments & crypto", "Financial products, banking, payments, digital assets, stablecoins and crypto infrastructure."),
 ("finance-legal-and-operations", "Finance, legal & business operations", "CFO practice, accounting, tax, legal operations, startup equity and operating systems."),
 ("education-and-public-good", "Education, civic tech & impact", "Learning, schools, public-interest technology, philanthropy and social impact."),
 ("real-estate-and-built-world", "Real estate & the built world", "Property, construction, housing, urban systems and the built environment."),
 ("sales-and-gtm", "Sales, GTM & customer success", "Sales strategy, go-to-market execution, revenue teams, support and customer success."),
 ("marketing-and-growth", "Marketing, brand & growth", "Marketing, positioning, founder brands, discoverability and growth tactics."),
 ("fundraising-and-pitches", "Fundraising, pitches & exits", "Raising capital, pitch practice, startup competitions, acquisitions and exits."),
 ("investors-and-capital", "Investors, funds & capital", "Investor perspectives, venture funds, angel investing, LP/GP conversations and capital allocation."),
 ("global-founders", "Global founders & cross-border growth", "International founder communities, immigration, market entry and cross-border expansion."),
 ("inclusive-communities", "Women & underrepresented communities", "Gatherings explicitly focused on women, queer builders and other underrepresented communities."),
 ("careers-and-leadership", "Careers, teams & leadership", "Hiring, talent, engineering leadership, people operations and career development."),
 ("founder-practice", "Founder practice & cofounders", "Starting and running a company, founder lessons, cofounder matching and founder support."),
 ("hackathons-and-builds", "Hackathons & hands-on builds", "General hackathons, buildathons and practical building sessions without a more specific primary subject."),
 ("demos-and-showcases", "Demos, launches & showcases", "General startup showcases, demo days, product launches and open demo sessions."),
 ("coffee-and-daytime-socials", "Coffee, breakfasts & daytime socials", "General morning meetups, coffees, brunches, lunches and informal daytime connections."),
 ("dinners-and-small-tables", "Dinners & small-table conversations", "General founder, investor and builder dinners, supper clubs and intimate meals."),
 ("mixers-and-happy-hours", "Mixers & happy hours", "General networking, receptions, happy hours and casual evening introductions."),
 ("parties-and-play", "Parties, games & culture", "Parties, concerts, comedy, board games, poker and cultural social events."),
 ("sports-and-outdoors", "Sports, walks & outdoors", "Runs, rides, hikes, sports, sailing and other active gatherings."),
 ("ai-perspectives", "AI perspectives & big questions", "Broad AI summits, public conversations and big-picture questions without a more specific title signal."),
 ("open-discovery", "Open houses, clubs & discovery", "Open houses, coworking, clubs and broadly titled gatherings whose subject is not clear from the title alone."),
]
# Ordered rules: narrowly stated purpose or domain first, general formats later.
RULES = [
 ("sports-and-outdoors", r"\b(padel|pickleball|tennis|basketball|h\.o\.r\.s\.e|surf(?:ing)?|hikes?|hiking|sail(?:ing)?|bike|biking|cycling|bouldering|boxing|hiit|pilates|workout|swim|strava|power walk|morning walk|walking tour|stroll|bridge walk|run club|running club|morning run|sunrise run|run and walk|run to coffee|slow run|tech walk|techwalk|group ride|balance sheet ride|coastal walk|backhands|boat party)\b|\brun(?:ning)? (?:with|for|&|meetup)\b|\b(run|walk|ride)\s*[|:]|\b(walk|run|sail|swim)\s*$"),
 ("wellbeing-and-longevity", r"\b(longevity|healthspan|wellness|wellbeing|well-being|nutrition|nervous system|mental health|metabolic|meditation|yoga|sauna|cold plunge|onsen|decompression|healing|nourish|reset|sleep(?:ing)?|human flourishing|human performance|self-trust|human os|burnout|balance|brain gains|brain fuel|brain optimization)\b"),
 ("health-and-biotech", r"\b(health\w*|biotech|bio|bioai|medicine|medical|doctors?|illness|proteins?|medtech|drug|clinical|patient\w*|physician\w*|pharma\w*|cancer|oncology|neuro\w*|braintech|neuroscience|fertility|biolog\w*|life sciences?|telehealth|biosensors|aging|biopunk|hospitals?|care at a distance)\b|next\.bio|bio x ai|ai x bio"),
 ("real-estate-and-built-world", r"\b(real estate|proptech|construction|pre-construction|built (?:world|environment)|housing|urban|cities|mortgage|property|homes?|rent)\b"),
 ("climate-and-frontier-tech", r"\b(climate|cleantech|clean tech|sustainab\w*|decarbon\w*|carbon|energy|nuclear|solar|power grid|grid|quantum|space(?:tech)?|aerospace|maritime|ocean|battery|batteries|fusion|green software|science|scientific|environmental)\b|power(?:ing)? (?:the )?(?:ai|compute|data)|power as fast|who will power|space based"),
 ("robotics-and-hardware", r"\b(robot\w*|hardware|physical ai|embodied|manufactur\w*|industrial|reindustrial\w*|deep[ -]?tech|hard[ -]?tech|sensors?|semiconductors?|chips?|wearables?|autonomous vehicles?|defense|defence|schematic|cyberdeck|mmwave|cad)\b"),
 ("fintech-and-payments", r"\b(fintech|banking|banks?|bankgpt|payments?|stablecoins?|crypto\w*|web3|blockchain|defi|tokenization|digital assets?|rwa|trader|trading|wealthtech|insurance|insurtech|agentic commerce|agents? (?:with|gets?) (?:a )?wallet|ai gets a wallet|agent economy)\b"),
 ("education-and-public-good", r"\b(education|edtech|schools?|students?|teachers?|learning (?:lab|science|future)|universit\w*|college|nonprofit\w*|charity|social impact|social good|civic|democracy|philanthrop\w*|public good|mission bit|youth|future we want)\b"),
 ("inclusive-communities", r"\b(women\w*|woman|female|queer|lgbt\w*|underrepresented|diversity|diverse|inclusion|inclusive|black founders|black builders|black tech|veterans|tech gals|build for her|her terms|shefundrais\w*|femhaus)\b"),
 ("global-founders", r"\b(global|international\w*|cross.borders?|market.entry|immigra\w*|visas?|us market|u\.s\.|scaling the us|in the us|beyond borders|without borders|europe\w*|european|latam|latino\w*|latina\w*|australia\w*|aussie|down under|japan\w*|india\w*|africa\w*|argentin\w*|mexic\w*|latvi\w*|korea\w*|canad\w*|brazil\w*|china|chinese|taiwan\w*|sweden|swedish|swiss|switzerland|zürich|zurich|polish|poland|israel\w*|isravalley|pakistan\w*|south asia\w*|asia.to.us|baltic|apac|uae|saudi|german\w*|germany|france|french|italian|italy|spain|spanish|turk\w*|ukrain\w*|asian|uk-us|uk to|próspera)\b"),
 ("finance-legal-and-operations", r"\b(cfos?|fp&a|finance leaders?|financial model|finance stack|finance workshop|accounting|accountants?|tax|audit|cap table|equity|compensation|comp|legal\w*|law(?:s|yers)?|regulations?|term sheets?|diligence|procurement|back office|back-office|compliance|contracts?|cost of scaling|cost management|revenue management|expense\w*|capital efficiency|balance sheet|trust & estate)\b"),
 ("security-and-governance", r"\b(security|securing|secure|cyber\w*|privacy|private data|safety|safer|safe|guardrails?|governan\w*|governing|regulat\w*|authorization|auth(?:entication)?|agent controls|control plane|human.cent(?:er|re)d|trust(?:ed|worthy)?|risk|liability|policymakers?|policy|responsible ai|alignment|ai on trial|ai rights|anti.distillation|hacked its makers)\b"),
 ("voice-and-conversation", r"\b(voice|voices|conversational|speech|audio|realtime|real-time conversation|translation ai|multilingual|conversation(?:al)? ai)\b|can you hear the difference"),
 ("creative-media", r"\b(creativ\w*|creators?|storytell\w*|film\w*|movies?|cinema|video|media|music\w*|artists?|painting|museums?|photograph\w*|narrative|content production|content creation|podcast\w*|animation|creatorthon|artech|arttech|artificial art)\b|make content|make me care|human vs. machine: the beat|content, not excuses"),
 ("consumer-and-commerce", r"\b(consumer|commerce|retail|marketplace\w*|shopping|beauty|fashion|couture|entertainment|gaming|game dev\w*|games industry|vr|xr|3d worlds|3d printed fashion|hospitality|foodtech|food tech|travel tech|experiences & play|live events|event tech|sports tech|sports startup)\b"),
 ("product-and-design", r"\b(product(?:s)?|design(?:ers?)?|ux|user experience|user research|user testing|ui|interfaces?|pmf|product.market fit|retention|cpo|talk to users|imagination layer)\b"),
 ("marketing-and-growth", r"\b(marketing|marketers?|brand\w*|growth|seo|geo|aeo|advertis\w*|adtech|influenc\w*|distribution|demand gen|demand-gen|demand generation|content|discoverab\w*|visibility|public relations|press|media buying|founder.led (?:content|brand)|loyalty)\b|chatgpt.famous|get found on ai|be the answer|doesn.t recommend your company"),
 ("sales-and-gtm", r"\b(gtm|go.to.market|sales|sell|selling|sdr|revenue|customers?|cx|support stack|commercializ\w*|partnerships?|buyers?|qbr|customer success)\b"),
 ("careers-and-leadership", r"\b(careers?|hiring|hire|talent|recruit\w*|jobs?|teams?|leadership|leaders?|executive presence|people (?:ops|operations|leaders)|hr|cto|chief of staff|managers?|management|promotion|employee|employment|fde|forward.deployed engineer|future of work|human agency.*work|work is|workforce)\b"),
 ("compute-and-cloud", r"\b(inference|compute|gpus?|datacenters?|data centers?|cloud|infra(?:structure)?|serverless|kubernetes|latency|ai factory|ai factories|ai economics|cost of ai|token econom\w*|compute econom\w*)\b"),
 ("data-memory-and-search", r"\b(data|databases?|lakehouse|retrieval|rag|memory|memories|context\w*|knowledge|search|vectors?|analytics|intelligence layer|knowledge twins|data moats)\b|what should ai remember"),
 ("coding-and-devtools", r"\b(cod(?:e|ing)|software|engineering|engineers?|developers?|devs|devtools?|devex|dx|observability|devops|mlops|apis?|debug\w*|programming|prs?|pull requests?|angular|react|typescript|javascript|terminal|software factories|agentic sdlc|ci/cd)\b|backlog to pr|what.s next for dx"),
 ("models-and-evaluation", r"\b(models?|evals?|evaluation|benchmark\w*|reasoning|training|reinforcement|fine.tun\w*|finetun\w*|llms?|research(?:ers)?|researchers|frontier science|world models?|self.improv\w*|interpretabil\w*|reinforcement learning|rl|continual learning|model wrangl\w*|distillation|diffusion|synthetic data|superintelligence)\b"),
 ("agents-and-automation", r"\b(agents?|agentic|mcp|multi.agent|automation|automated|workflow\w*|orchestrat\w*|harness|computer.use|autonomous|tool.use|tools for ai)\b"),
 ("enterprise-ai", r"\b(enterprise|ai (?:adoption|transformation|readiness|delivery|operations|at work)|business ai|ai for business|humanising ai|ai.native (?:company|organization|business)|ai.organization|ai.*(?:business|work)|organization.*ai|business.*ai|ai.native in half|ai strategy|roi|ai operating|ai in production|prototype to production|the ai era|ai-enabled)\b"),
 ("fundraising-and-pitches", r"\b(fundrais\w*|raising|raise|raised|pitch(?:es)?|pitching|pitchdeck|pitch deck|seed round|funding|term sheet|acqui\w*|exit(?:ed|s)?|post.exit|liquidity|sell your startup|startup award|startup competition|startup battle|startup battlefield|ipos?|spacs?|m&a)\b"),
 ("investors-and-capital", r"\b(investment|investing|investments|investor (?:perspective|outlook|strategy|briefing|debriefing)|allocators?|allocation|family offices?|lps?|gps?|vc fund|venture fund|angel check|angel invest\w*|venture capital|venture deals|venture lab|capital summit|future of capital|frontier investing|portfolio|fund managers?|accredited|qualified purchaser|capital markets|investor.*panel|founder.*investor.*panel)\b"),
 ("founder-practice", r"\b(co.?founders?|founder (?:playbook|journey|story|stories|lesson|lessons|circle|coaching|office hours|bottleneck)|bootstrapp\w*|startup playbook|serial founder|founder.led|founder.s journey|founder mindset|first.time founder|solo founder|serial entrepreneur|entrepreneurship|founder lessons|startup journey|from idea|zero to|zero.to|0.to.1|0-to-1|building a company|start(?:ing)? a company|startup essentials|growth.stage playbook|accountability|negotiation\w*|founder table|founder reset|founder (?:off|open)|founders on|founder fireside|ask a founder|founder mistakes|founder.led)\b"),
 ("hackathons-and-builds", r"\b(hack\w*|buildathon\w*|build.a.thon|build night|build with|build your|build a|build an|workshop\w*|hands.on|vibe coding|builders? lab|build lab|live build|build for|b@bhacks|speedhacks)\b|/build|sip & ship"),
 ("demos-and-showcases", r"\b(demos?|showcases?|launch(?:es|ing)?|show.n.tell|faire|startup challenge|open demo)\b|\[demoscene\]"),
 ("sports-and-outdoors", r"\b(walk|running|run|ride|golf|fleet week|fleetweek|flyover|sailing|sail|bowling|boating|frisbee|outdoor|mount tam|beach|park|hockey|warriors|giants|motorworks)\b"),
 ("parties-and-play", r"\b(party|parties|afterparty|after.party|gala|rave|masquerave|dj|dance|salsa|comedy|punchlines?|poker|chess|mahjong|game night|games|geoguessr|murder mystery|arcade|karaoke|singles|date night|festival|concert|music|idol|birthday|costume|mingle.*bingo|bingo|laughbytes|laughter|soiree|soirée|swansong|sound|block party|ball|talent show)\b"),
 ("dinners-and-small-tables", r"\b(dinners?|supper|dining|omakase|chef|tasting|michelin|table for|founder.s table|roundtable dinner|salon|small table|private table|round table)\b"),
 ("coffee-and-daytime-socials", r"\b(coffee|coffees|breakfast|brunch|lunch|luncheon|cafe|café|matcha|chai|bagels?|waffles?|croissant\w*|tea|burritos?|morning|lemonade|boba|brew(?:s|bird)|juice|fuel)\b"),
 ("mixers-and-happy-hours", r"\b(mixers?|networking|happy hour|cocktails?|drinks?|beers?|brews?|reception|mingle|social|meetup|meet.up|gathering|connect|connections|connectors?|hangout|hang|after hours|rooftop|kick.?off|off the record|after dark|in the bay|meet|night|bbq|barbecue|pints?|pub|meet.n.mingle|speakeasy|sip|pour|wine)\b"),
 ("ai-perspectives", r"\b(ai|agi|intelligence|intelligent|claude|deepmind|mistral|chatgpt|humans?|humanity|machine|machines|future of|frontier|tomorrow)\b"),
]
# Overrides are keyed by exact public titles for transparent review and updates.
OVERRIDES = {
    "ur +1 is a stranger": "mixers-and-happy-hours",
    "Bria × fal × LTX: What's New in Open-Weights Pipelines": "models-and-evaluation",
    "TokenTechWalk w/ Vonage": "sports-and-outdoors",
    "Matched by Verci": "mixers-and-happy-hours",
    "Matched by NEXA - SF Quest Week": "mixers-and-happy-hours",
    "From Series A to Scale: Scaling Without Losing Control": "founder-practice",
    "Skills That Matter": "careers-and-leadership",
    "Why Investors Say No + In The Ring with an Investor": "fundraising-and-pitches",
    "IRL Events Re-imagined": "consumer-and-commerce",
    "The Leap: From Executive to Founder (invite only)": "founder-practice",
    "Inside the Executive Suite - Ask Me Anything": "careers-and-leadership",
    "The Builder's Table with Adobe for Startups": "dinners-and-small-tables",
    "Blazel Hot Sauce Competition": "parties-and-play",
    "Confronting Genocide in the Tech and Startup World": "education-and-public-good",
    "From 0 to 100,000 Devices": "robotics-and-hardware",
    "RedBridge Lisbon": "global-founders",
    "Strike It Rich: A Gold Rush Scavenger Hunt": "parties-and-play",
    "The New Executive Playbook": "careers-and-leadership",
    "THE STARTUP JOURNEY FIRESIDE CHAT": "founder-practice",
    "Hot Takes Open Mic": "parties-and-play",
    "Powering the Golden Dome by Imagining Forward": "robotics-and-hardware",
    "Sushi-Making with Fearn and Kindred Ventures": "parties-and-play",
    "Building the Interactive Worlds": "consumer-and-commerce",
    "See you behind the mask": "parties-and-play",
    "SOULCYCLE CLASS: Uplane x IM8 🟦": "sports-and-outdoors",
    "Structuring Investor Agreements: What Founders Need to Know": "finance-legal-and-operations",
    "Faith Driven Investors & Founders": "founder-practice",
    "Never Finished: The Next Chapter | Conversations on Reinvention": "careers-and-leadership",
    "ProductCon": "product-and-design",
    "Recharge with OpenRouter": "wellbeing-and-longevity",
    "The Founder's Story Stack": "marketing-and-growth",
    "Unprompted: Founders building the next thing people do for fun": "consumer-and-commerce",
    "Leading Through Transformational Change": "careers-and-leadership",
    "AWS Expert Booth - #Startups@AWS": "compute-and-cloud",
    "UK Unicorns & Rising Stars": "global-founders",
    "what's next in finance": "fintech-and-payments",
    "$0 to $2.6B in 12 Months. Here’s How.": "founder-practice",
    "Founder and Investor Lounge": "mixers-and-happy-hours",
    "a16z Perennial - Founders Financial Future Collective": "finance-legal-and-operations",
    "Flying Car eVTOL challenges and potential talk": "robotics-and-hardware",
    "Private Plane Tour of SF with Airwallex": "sports-and-outdoors",
    "🤝 MATCH HOUSE San Francisco": "mixers-and-happy-hours",
    "The Oasis @ SF Tech Week - Finding Ikigai": "wellbeing-and-longevity",
    "Every Token Has a Price": "compute-and-cloud",
    "Inception Studio - The Founder Game ARG": "parties-and-play",
    "Income & Spending Clinic: Afford San Francisco": "finance-legal-and-operations",
    "20,000 Emails. Two Replies. The 25-Minute Masterclass on Aiming Before You Automate": "sales-and-gtm",
    "UK Founder Pitch": "global-founders",
    "&cruise — SF ↔ Tokyo": "global-founders",
    "Heidi Pop-Up: Calling All Builders 🚀 - Gelato, Swag & Chats": "coffee-and-daytime-socials",
    "Prompted: Wharton Tech Toks x LSPT": "education-and-public-good",
    "Smartlead x Pump: Scaling Without Scaling Headcount": "enterprise-ai",
    "Build, Buy, or Partner?": "founder-practice",
    "CEO Confessions: Town, Augment and their Coaches": "careers-and-leadership",
    "From ore to orbit": "climate-and-frontier-tech",
    "Keeping Up With Tech: What Makes a Story?": "creative-media",
    "Morph-a-thon : Describe Your App, Close Your Laptop": "hackathons-and-builds",
    "Open Capital Frontiers": "investors-and-capital",
    "Speed-dating #Let Fo do the first move": "mixers-and-happy-hours",
    "Tech Roast Show [Presented by Rippling]": "parties-and-play",
    "Zen & The Art of Self Mastery": "wellbeing-and-longevity",
    "Building the Onchain Capital Stack": "fintech-and-payments",
    "COLM HappyHour": "mixers-and-happy-hours",
    "How SF's Corner Stores Won the World Cup": "consumer-and-commerce",
    "Scaling Innovation Across Borders": "global-founders",
    "CZ/SK @": "global-founders",
    "HACpy Hour @ HAC": "mixers-and-happy-hours",
    "Killing Meetings with Zoom [IRL]": "enterprise-ai",
    "Rethinking Car Service": "consumer-and-commerce",
    "Deel x Rod Wave: Founders' Celebration w/ Deel & AWS": "parties-and-play",
    "The Meaningful Handshake Experiment": "mixers-and-happy-hours",
    "F**kUp Nights with ValkaAI": "founder-practice",
    "How to Govern the Moon": "climate-and-frontier-tech",
    "How to rage-bait investors 101": "fundraising-and-pitches",
    "Naming What's Next: From Invention to Culture": "marketing-and-growth",
    "VIP Investor & Founder Lounge": "mixers-and-happy-hours",
    "NOCHE DE LOTERÍA": "parties-and-play",
    "Open to Work: The Game Show": "careers-and-leadership",
    "speedrun alumni reunion & officewarming": "mixers-and-happy-hours",
    "Antler x Every.io Founder Lounge": "mixers-and-happy-hours",
    "Unplug & Recharge": "wellbeing-and-longevity",
    "3rd San Francisco GREEN Beltway Rollout 8m/13km": "sports-and-outdoors",
    "Beyond Unicorns": "founder-practice",
    "What does your function look like in 2028?": "careers-and-leadership",
    "3M to 100M Users: How Gamma Actually Did It": "product-and-design",
    "Founder Investor Day at Finix HQ": "mixers-and-happy-hours",
    "Office Sanctuary at Alma Office": "wellbeing-and-longevity",
    "One operating system for your firm and every company you own.": "finance-legal-and-operations",
    "Impactpalooza": "education-and-public-good",
    "GoCar Founders Tour": "sports-and-outdoors",
    "How to Collaborate with Big Tech Companies": "sales-and-gtm",
    "Your Idea Is Only as Good as How You Tell It": "marketing-and-growth",
    "2026 Tech Week St Francis Yacht Club": "sports-and-outdoors",
    "The Exchange: Your Next Opportunity Is in the Room": "mixers-and-happy-hours",
    "ALSO TEST SPIN": "sports-and-outdoors",
    "Inside the First Round w/ Khosla, Antler, Floodgate": "fundraising-and-pitches",
    "LockMCP": "security-and-governance",
    "THE MONEY ROOM: What Actually Gets Funded Today": "fundraising-and-pitches",
    "Headshots, Headlines + Hot Seats": "marketing-and-growth",
    "Brown Girls on the Rise - #SF Tech Week": "inclusive-communities",
    "Fund or Fold - How VCs Actually Decide": "investors-and-capital",
    "Secondaries are now Primary": "investors-and-capital",
    "See You Outside: The Future Is IRL": "consumer-and-commerce",
    "Sushi & Sandbox-maxxing": "dinners-and-small-tables",
    "Basecamp and Bubbles": "mixers-and-happy-hours",
    "Builder, Backer, Advisor: Gokul Rajaram on All Three Sides of the Table": "founder-practice",
    "Legendary Ventures": "investors-and-capital",
    "Love at First Slide with Gamma & Atlassian": "creative-media",
    "Scalability Lab at Asana HQ": "enterprise-ai",
    "Spotlight on Scotland": "global-founders",
    "Swag Lab: Make It & Take It": "parties-and-play",
    "VC x Founder Match": "fundraising-and-pitches",
    "BioPioneers x VCVillage": "health-and-biotech",
    "Building a $7B Unicorn: Deepika of Commure and Investor Varsha": "founder-practice",
    "Open Circuit: The Founders Exhibit": "demos-and-showcases",
    "tech is politics, politics is tech with Sway": "security-and-governance",
    "Analog Extravaganza w/ Fin, Vanta, Fireworks, Linear, Dust": "parties-and-play",
    "Strategy as an Emotional Act: An Interactive Practice for Changemakers": "careers-and-leadership",
    "Who Will Own the Future?": "ai-perspectives",
    "Let’s Take This Offline": "mixers-and-happy-hours",
    "The Annual Table 26u26": "dinners-and-small-tables",
    "Live Blacksmithing with CoreWeave": "parties-and-play",
    "The PULL x Macy’s Market Activation": "consumer-and-commerce",
    "I AM UNSEXY. AND I LIKE IT: The Passion Projects of Founders Who Build What They Love": "founder-practice",
    "Private Evening for Series A+ Founders": "mixers-and-happy-hours",
    "rsvpmaxxing: the last RSVP of SF Tech Week 🪩": "parties-and-play",
    "The Penthouse Affair By Founders Paddock": "parties-and-play",
    "Get Your Company Featured to 1,000 Builders": "marketing-and-growth",
    "CarShowAndWine": "parties-and-play",
    "Oyster Bake 2026": "dinners-and-small-tables",
    "New Friendship Tech Week": "mixers-and-happy-hours",
    "Sweat Out Tech Week": "sports-and-outdoors",
    "staaake Skybar Founders Hangover Closing Event": "mixers-and-happy-hours",
    "AI Readiness Audit Workshop": "enterprise-ai",
    "Spill the Tea, Not Your Energy: Council Capital x J.P. Morgan High Tea Experience": "coffee-and-daytime-socials",
    "The AI-Native Fund: Rebuilding Investment Management for the Agent Era": "investors-and-capital",
    "Stanford AI Lab": "models-and-evaluation",
    "Context Party x Interf": "parties-and-play",
    "Building on Hard Ground: AI, Child Safety, and the CSAM Problem": "security-and-governance",
    "THE SCIENCE WORKS. THE ECONOMICS DON’T.": "climate-and-frontier-tech",
}

# A second review corrects ambiguous brand words and broad first-pass matches.
OVERRIDES.update({
    "CRITICAL MINERALS NIGHT: From AI Models to Mineral Assets in the Midst of a Mineral Super Cycle": "climate-and-frontier-tech",
    "PRE-INCORPORATION TRAINING DAY: CREATE THE NEXT OPENAI FOUNDATION": "founder-practice",
    "Private Gallery Evening: Founders, Investors, and Researchers": "parties-and-play",
    "Vectors Capital 2026 AGM & VC Happy Hour": "investors-and-capital",
    "Hi, Cofounder: an IRL cofounder search": "founder-practice",
    "The Search for Durable Advantage in AI": "ai-perspectives",
    "AI in FinCrime Mixer hosted by Unit21 & FS Vector": "fintech-and-payments",
    "Cyberglam NFC Nail Party": "consumer-and-commerce",
    "Cybernetics: Bridging Human, Machine & Mind": "robotics-and-hardware",
    "The New Finance: AI. Data. Talent. Governance. Scale.": "finance-legal-and-operations",
    "Human-in-the-Loop: Run Smarter Small Businesses with trust": "enterprise-ai",
    "How to Make Trust Your GTM Advantage - Keynote by Court Lorenzini": "sales-and-gtm",
    "Seed Founders: Free Working Space on Market St.": "open-discovery",
    "Physical AI Paper Club & Science Dinner": "robotics-and-hardware",
    "The Minimum Viable Avatar: Scientific Method for Customer Understanding": "product-and-design",
    "Under the Hood: AI meets Behavioral Science": "ai-perspectives",
    "INTERFACE: Hack the Space Between": "product-and-design",
    "The Science of Speed | Tech Week Meets Fleet Week": "sports-and-outdoors",
    "Future of Work Hackathon: Building from the Farm @Stanford University": "hackathons-and-builds",
    "GTM for Enterprise Growth w/ Equity Angels + Wells Fargo": "sales-and-gtm",
    "Supporting Tech Teams Through Rapid Growth": "careers-and-leadership",
    "How Much Should AI Know About You?": "security-and-governance",
    "AI Pay Summit": "fintech-and-payments",
    "Making Waves: AI x Finance on the Bay": "finance-legal-and-operations",
    "Disrupting Group Travel: How AI is transforming Coordination": "consumer-and-commerce",
    "Stop losing money on events: How we use AI to make $10k per event": "marketing-and-growth",
    "Future of Open Source": "coding-and-devtools",
    "Machines with Money": "fintech-and-payments",
    "AI Heist Challenge with Cogent x Modal x LangChain": "security-and-governance",
    "Identity, Entity, AI and the New Graph": "data-memory-and-search",
    "Prompts vs. Presence: Reclaiming Cognitive Bandwidth in the Age of AI": "wellbeing-and-longevity",
    "Human v. AI Cold Call": "sales-and-gtm",
    "5 AI Risks Are Killing Your Deals. The fifth is why the first 4 keep coming back.": "sales-and-gtm",
    "Making hard decisions in a world of AI and constant change": "careers-and-leadership",
    "Beyond the AI Hype: What Investors Are Backing": "investors-and-capital",
    "Signals for What’s Next: AI, Prediction Markets & Emerging Technology": "fintech-and-payments",
    "AI Tech Day East meets West": "global-founders",
    "Body Intelligence Summit 3.0": "wellbeing-and-longevity",
    "Win Q4 on Meta with AI": "marketing-and-growth",
    "Automotive x AI: The Future of Mobility": "robotics-and-hardware",
    "Blitzscaling with AI featuring Open AI, YC, A16z Speedrun": "enterprise-ai",
    "Executive Roundtable: Future of People Tech": "careers-and-leadership",
    "Forward-Deployed AI Forum": "coding-and-devtools",
    "AI Tool Evaluations with AICamp, ScaleKit, and Workato": "models-and-evaluation",
    "Decant the Decision on Your AI-Native Finance Tech Stack: Build vs. Buy with Tabs & Campfire": "finance-legal-and-operations",
    "Double Date: Bring Your AI Plus-One": "consumer-and-commerce",
    "Can AI File Your Patent? What Founders Should Know": "finance-legal-and-operations",
    "THE 1,000 STRANGERS EXPERIMENT 5 scoops of ice cream, 5 introductions and human connection.": "mixers-and-happy-hours",
    "Human-in-the-Loop Is Already Broken. Here's What Replaces It.": "agents-and-automation",
    "You, the Frontier Professional": "careers-and-leadership",
    "AI in Strategic Finance": "finance-legal-and-operations",
    "AI Native - Hecho en Mexico": "global-founders",
    "Building the Physical World with AI": "robotics-and-hardware",
    "AI x Government": "education-and-public-good",
    "Your Brain on AI": "wellbeing-and-longevity",
    "AI for Finance Summit 2026 SF": "finance-legal-and-operations",
    "AI from the Rest of the World": "global-founders",
    "From a Data Swamp to a Data Agent You Can Trust: What It Actually Takes": "data-memory-and-search",
    "TECH WEEK: Knowledge Twins — a Swiss breakfast on private memory for agents # SFTechWeek": "data-memory-and-search",
    "Build a Company Brain: AI Agents with Memory, Context and Secure Access": "data-memory-and-search",
    "The Founder Reset: What Your Company Data is Worth": "data-memory-and-search",
    "Creative Data Hackathon": "data-memory-and-search",
    "Data Partnerships Happy Hour": "data-memory-and-search",
    "Multiplayer AI at Work: Shared Context, Team Workflows, and the Future of Collaboration": "enterprise-ai",
    "Building Forward After Accelerator Turndowns": "founder-practice",
    "From Reviews to Intelligence: The Next Generation of Beauty Discovery.": "consumer-and-commerce",
    "Shopping 3.0: the AI Commerce Hackathon with Arcade": "consumer-and-commerce",
})

# Final ambiguity audit: avoid treating exercise as model training, brand names as
# geography, or unknown titles as evidence of a technical subtopic.
OVERRIDES.update({
    "Founder-Led Strength Training": "sports-and-outdoors",
    "AI Strikes Oil II: World Models Go Downhole": "climate-and-frontier-tech",
    "Private Dinner with Growth Equity VC": "investors-and-capital",
    "The Trust Problem AI Created For B2B Marketers": "marketing-and-growth",
    "“Find Your Match-a” by 500 Global x Zendesk": "mixers-and-happy-hours",
    "The Next Layer of AI: From Models to Real-World Intelligence TFOT: Global Innovation Summit": "models-and-evaluation",
    "The Future of Global Money Movement": "fintech-and-payments",
    "Mothers in Tech: Juggling Career and Motherhood in the Age of AI": "inclusive-communities",
    "Private cycle class for the TA & HR community.": "sports-and-outdoors",
    "The Tech Leaders Suite: Warriors x SFTechWeek": "sports-and-outdoors",
    "Who Will Own the Future?": "open-discovery",
    "Human-in-the-Loop Is Already Broken. Here's What Replaces It.": "enterprise-ai",
})

def classify(event):
    title=event['title']
    if title in OVERRIDES:
        return OVERRIDES[title]
    for slug,pattern in RULES:
        if re.search(pattern,title,re.I):
            return slug
    return 'open-discovery'

def build_collections(events):
    """Return a complete primary partition in display order without writing files."""
    groups={slug:[] for slug,_,_ in COLLECTIONS}
    for event in sorted(events, key=lambda e: (e['date'], e.get('start_time') or '99:99', e['title'].casefold(), e['id'])):
        groups[classify(event)].append(event['id'])
    catalog={'method':METHOD,'collections':[{'id':slug,'name':name,'description':description,'event_ids':groups[slug]} for slug,name,description in COLLECTIONS]}
    flat=[eid for c in catalog['collections'] for eid in c['event_ids']]
    assert len(flat)==len(events)==len(set(flat)), 'Each event must appear exactly once'
    assert set(flat)=={e['id'] for e in events}, 'Coverage must exactly match events.json'
    assert len(groups)==len(COLLECTIONS), 'Collection IDs must be unique'
    assert all(groups.values()), 'Remove empty categories or improve classification'
    assert set(OVERRIDES.values()) <= set(groups), 'Every override must name a collection'
    return catalog

def main():
    events=json.loads((ROOT/'data/events.json').read_text())
    catalog=build_collections(events)
    (ROOT/'data/collections.json').write_text(json.dumps(catalog,ensure_ascii=False,indent=2)+'\n')
    for collection in catalog['collections']:
        print(f"{len(collection['event_ids']):4}  {collection['id']}")
    print(f'{len(events)} events in {len(COLLECTIONS)} collections')

if __name__=='__main__':
    main()
